apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
  namespace: monkey-ingress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: crawler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crawler
    spec:
      containers:
        - name: crawler
          image: slowlight50/stock-crawler:8
          env:
          - name: key
            value: "AKIA4JCZIACQGPXH52HC"
          - name: secret
            value: "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"
          - name: s3
            value: "monkey-crawler-bucket"
          resources: {}
