apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: monkey-space
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dev210/monkey-frontend:latest
        ports:
        - containerPort: 80
        resources: {}
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: monkey-space
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 80
