apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: monkey-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: user
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user
    spec:
      containers:
      - name: user
        image: dev210/monkey-user:1
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "monkey-user.crxm811ebs75.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "monkey321"
        - name: DATABASE
          value: "monkeyUser"
        - name: SECRET
          value: "SESACSESACSESACSESACSESACSESACSESACSESACSESACSESACSESAC"
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: monkey-ingress
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: user
  ports:
  - port: 8082
    targetPort: 80
    protocol: TCP